system dos4g
option map
option stack=90k
option u
name duke3d
file game,actors,gamedef,global,menues,player,premap,sector,sounds,rts,config
file build\engine,build\cache1d,build\mmulti,build\a,animlib
library audio_wf.lib,mact\mact386.lib,butwcd4.lib
